version: "2.23.3-desktop.2"

services:
  frontend:
    build:
      context: ./front
    ports:
      - "5173:5173"
    command: npx vite --host

  backend:
    build:
      context: ./back
    ports:
      - "5000:5000"
